server:
  port: 7700
spring:
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka  

# enable all actuator endpoints for testing (review this for real deployments)
management.endpoints.web:
  include: '*'